version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - VITE_HOST=0.0.0.0
    networks:
      - app-network
    depends_on:
      - config-server

  config-server:
    build:
      context: ./cinematix-config-server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - config-data:/app/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  config-data: